#define API_HOSTNAME    @"teaplaza.maimaicha.com"
#define API_BASEURL     @"api"
#define API_FORMAT      @"json"
#define API_METHOD      @"GET"
#define API_KEY         @"b4a4ef31a8b9acd866ef2dfb754ce3e6"
#define SYS_VERSION     @"1.0"
#define UM_APPKEY       @"4fab36cf527015375d000049"
#define UM_SHARETEXT    @"茶广场包括茶百科、开心茶园、单店ERP、买买茶等多款茶行业应用。即刻下载，与众多茶叶爱好者（茶叶经营者）共同体验精品应用！马上来下载http://teaPlaza.maimaihca.com"
